### ISSUE TITLE
import问题

### ISSUE THREAD

**Issue by littleboy12580** [littleboy12580/learning_python#2]
在使用import时，如果要导入的python文件被命名为1.py，2.py之类的就会报错，说是无效字符。这是什么原理呢？文件命名需要注意哪些问题？

**Comment by hotbaby** [comment]
``` python
import sys
print(sys.path)
```

查看moudle的搜索路径，同时该路径是可以定制的。
另外，python module,  package是有自己的命名规范的，在写testcase时，要表达原意，不要用1, 2去命名。
[python 编码规范](https://www.python.org/dev/peps/pep-0008/)
