### ISSUE TITLE
字符串书写问题

### ISSUE THREAD

**Issue by littleboy12580** [littleboy12580/learning_python#3]
在书上看到的一段代码

> > > msg="""aaaaaaa
> > > bbb'''bbbbbbbb""bbbbb'bbbb
> > > cccccccccccc"""
> > > msg
> > > 输出的结果是：'aaaaaaa\nbbb\'\'\'bbbbbbbb""bbbbb\'bbbb\ncccccccccccc'
> > > 这是个什么原理？

**Comment by hotbaby** [comment]
在Python交互式shell下，msg作为一个字符串对象，并不会格式化，可以使用`print(msg)`进行格式化输出。
